server:
  port : 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8070/eureka/

# to enable actuator endpoints /health /info
# http://localhost:8072/actuator/health/
management:
  endpoints:
    web:
      expose: "*"
